/*
 * generated by Xtext 2.24.0
 */
package za.org.cair.logic_app.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import za.org.cair.logic_app.LogicLangRuntimeModule;
import za.org.cair.logic_app.LogicLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LogicLangIdeSetup extends LogicLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LogicLangRuntimeModule(), new LogicLangIdeModule()));
	}
	
}
