/*
 * generated by Xtext 2.24.0
 */
package za.org.cair.logic_app.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class LogicLangWebModule extends AbstractLogicLangWebModule {
}
