/*
 * generated by Xtext 2.24.0
 */
package za.org.cair.logic_app.web;

import java.net.InetSocketAddress;
import org.eclipse.jetty.annotations.AnnotationConfiguration;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.util.log.Slf4jLog;
import org.eclipse.jetty.webapp.Configuration;
import org.eclipse.jetty.webapp.MetaInfConfiguration;
import org.eclipse.jetty.webapp.WebAppContext;
import org.eclipse.jetty.webapp.WebInfConfiguration;
import org.eclipse.jetty.webapp.WebXmlConfiguration;

/**
 * This program starts an HTTP server for testing the web integration of the DSL.
 */
public class ServerLauncher {
	public static void main(String[] args) {
		int port = 8003; // default port
		if (args.length > 0) {
			port = Integer.parseInt(args[0]);
		}
		// listening on all interfaces so that external connections can access the app inside a container
		Server server = new Server(new InetSocketAddress("0.0.0.0", port));
		WebAppContext ctx = new WebAppContext();
		ctx.setResourceBase("src/main/webapp/");
		ctx.setWelcomeFiles(new String[] {"index.html"});
		ctx.setContextPath("/");
		ctx.setConfigurations(new Configuration[] {
			new AnnotationConfiguration(),
			new WebXmlConfiguration(),
			new WebInfConfiguration(),
			new MetaInfConfiguration()
		});
		ctx.setAttribute(WebInfConfiguration.CONTAINER_JAR_PATTERN,
			".*/za\\.org\\.cair\\.logic_app\\.web/.*,.*\\.jar");
		ctx.setInitParameter("org.eclipse.jetty.servlet.Default.useFileMappedBuffer", "false");
		server.setHandler(ctx);
		Slf4jLog log = new Slf4jLog(ServerLauncher.class.getName());
		try {
			server.start();
			log.info("Server started " + server.getURI() + "...");
			new Thread() {

				public void run() {
					try {
						log.info("Press enter to stop the server...");
						int key = System.in.read();
						if (key != -1) {
							server.stop();
						} else {
							log.warn(
									"Console input is not available. In order to stop the server, you need to cancel process manually.");
						}
					} catch (Exception e) {
						log.warn(e);
					}
				}

			}.start();
			server.join();
		} catch (Exception exception) {
			log.warn(exception.getMessage());
			System.exit(1);
		}
	}
}
