/*
 * generated by Xtext 2.24.0
 */
package za.org.cair.logic_app.tests

import com.google.inject.Inject
import java.io.BufferedReader
import java.io.InputStreamReader
import org.eclipse.emf.ecore.EObject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import za.org.cair.logic_app.logicLang.Model
import za.org.cair.logic_app.logicLang.Implication
import static org.junit.Assert.assertThat
import static org.hamcrest.CoreMatchers.instanceOf

@ExtendWith(InjectionExtension)
@InjectWith(LogicLangInjectorProvider)
class LogicLangParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			prop (A) | ~(~C & ~D) -> (C|D) <-> A
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		//println(dump(result, ""))
	}
	
	@Test
	def void birdExample() {
		val result = parseHelper.parse(readTestFile("test1.logic"))
		
		Assertions.assertEquals(6, result.propositions.length)
		
		val prop1 = result.propositions.get(0)
		assertThat(prop1, instanceOf(Implication))
		
	}
	
	def static String readTestFile(String fileName){
		val reader = new BufferedReader(new InputStreamReader(
			Thread.currentThread().getContextClassLoader().getResourceAsStream(fileName)
		))
		val builder = new StringBuilder();
		var line = "";
		while((line = reader.readLine()) !== null){
			builder.append(line).append("\n")
		}
		return builder.toString()
	}
	
	// credit: https://stackoverflow.com/a/35116799/3900981
	def static String dump(EObject mod_, String indent) {
	    var res = indent + mod_.toString.replaceFirst ('.*[.]impl[.](.*)Impl[^(]*', '$1 ')
	
	    for (a :mod_.eCrossReferences)
	        res += ' ->' + a.toString().replaceFirst ('.*[.]impl[.](.*)Impl[^(]*', '$1 ')
	    res += "\n"
	    for (f :mod_.eContents) {
	        res += f.dump (indent+"    ")
	    }
	    return res
	}
}
