/*
 * generated by Xtext 2.24.0
 */
package za.org.cair.logic_app;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogicLangRuntimeModule extends AbstractLogicLangRuntimeModule {
}
