
name: Build CLI logic lang compiler

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} # hash poms
        restore-keys: ${{ runner.os }}-m2

    - name: Standard compile
      run: mvn compile

    - name: Set up ant packaging
      run: ./pre-ant.sh
      shell: bash
      working-directory: ./dist

    - name: Ant packaging
      run: ant -f antpack.xml
      working-directory: ./dist

    - name: Store fat jar artifact
      uses: actions/upload-artifact@v1
      with:
        name: logic-compiler.jar  # name of the artifact
        path: dist/logic-compiler.jar
      
