# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test HOL reasoner integration

on:
  workflow_run:
    workflows: ["Build CLI logic lang compiler"]
    types:
      - completed

jobs:
  sat4j:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Download compiler
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: cli_generator.yml
        name: logic-compiler.jar  # artifact name
        path: ./
    - name: Get sat4j
      run: wget http://download.forge.ow2.org/sat4j/sat4j-pb.jar -O sat4j.jar
    - name: Setup workspace 1
      run: cp -r za.org.cair.logic_app/src/test/resources/sat ./
    - name: Setup workspace 2
      working-directory: ./sat
      run: |
        ls -1 *.logic | while read line; do
          echo 'config solver="sat4j"' >> $line
        done
    - name: Run logic satisfiability 1
      run: java -jar logic-compiler.jar sat/problem_sat.logic result.txt
    - name: Check for correct output 1
      run: diff result.txt sat/solution_sat.txt  # will fail if diffs
    - name: Quick cleanup
      run: rm result.txt
    - name: Run logic satisfiability 2
      run: java -jar logic-compiler.jar sat/problem_unsat.logic result.txt
    - name: Check for correct output 2
      run: diff result.txt sat/solution_unsat.txt


